site_name: MeasureSoftGram 2023.2

repo_name: '2023.1_G2_Logico_OptaSoftware'
repo_url: 'https://github.com/fga-eps-mds/2023.2-MeasureSoftGram-DOC'

theme:
  name: material
  language: 'pt'
  palette:
    primary: blue grey

nav:
  - Início: index.md
