site_name: MeasureSoftGram 2023.2

repo_name: '2023.2-MeasureSoftGram-DOC'
repo_url: 'https://github.com/fga-eps-mds/2023.2-MeasureSoftGram-DOC'

theme:
  name: material
  language: 'pt'
  logo: assets/logo.svg
  favicon: assets/logo.svg
  palette:
    primary: blue grey

nav:
  - Início: index.md
  - Planejamento:
    - Metodologias: planejamento/metodologias.md
  - Sprints:
    - sprint 00: sprints/sprint00.md
  - Tabelas:
    - Tabela de Conhecimentos: tabelas/heatmap_conhecimentos.md
    - Heatmap de Horários: tabelas/heatmap_horarios.md
  - Documentos:
    - Arquitetura: documentacao/arquitetura.md
  - Diagramas:
    - Diagrama Entidade-relacionamento: diagramas/diagrama_entidade_relacionamento.md
  - Guia de Contribuição: 
    - Política de Commits: guia_contribuicao/politica_commits.md
