site_name: MeasureSoftGram 2023.2

repo_name: '2023.2-MeasureSoftGram-DOC'
repo_url: 'https://github.com/fga-eps-mds/2023.2-MeasureSoftGram-DOC'

theme:
  name: material
  language: 'pt'
  logo: assets/logo.svg
  favicon: assets/logo.svg
  palette:
    primary: blue grey

nav:
  - Início: index.md
  - Planejamento:
    - Metodologias: planejamento/metodologias.md
    - Plano de Custos: planejamento/plano_custos.md
  - Reuniões:
    - Reunião 06/09: atas/reuniao1.md
    - Reunião 12/09: atas/reuniao2.md
    - Reunião 13/09: atas/reuniao3.md
    - Reunião 18/09: atas/reuniao4.md
    - Reunião 20/09: atas/reuniao5.md
    - Reunião 25/09: atas/reuniao6.md
    - Reunião 26/09: atas/reuniao7.md
    - Reunião 27/09: atas/reuniao8.md
    - Reunião 28/09: atas/reuniao9.md
    - Reunião 29/09: atas/reuniao10.md
    - Reunião 30/09: atas/reuniao11.md
    - Reunião 02/10: atas/reuniao12.md
    - Reunião 03/10: atas/reuniao13.md
    - Reunião 04/10: atas/reuniao14.md
  - Sprints:
    - Sprint 00: sprints/sprint00.md
  - Tabelas:
    - Tabela de Conhecimentos: tabelas/heatmap_conhecimentos.md
    - Heatmap de Horários: tabelas/heatmap_horarios.md
  - Documentos:
    - Arquitetura: documentacao/arquitetura.md
  - Gestão de Projetos:
    - Plano de risco: gestao_projetos/plano_risco.md
  - Diagramas:
    - Diagrama Entidade-relacionamento: diagramas/diagrama_entidade_relacionamento.md
  - Guia de Contribuição: 
    - Política de Commits: guia_contribuicao/politica_commits.md
