site_name: MeasureSoftGram 2023.2

repo_name: '2023.2-MeasureSoftGram-DOC'
repo_url: 'https://github.com/fga-eps-mds/2023.2-MeasureSoftGram-DOC'

theme:
  name: material
  language: 'pt'
  logo: assets/logo.svg
  favicon: assets/logo.svg
  palette:
    primary: blue grey

nav:
  - Início: index.md
  - Planejamento:
    - Tabela de Conhecimentos: tabelas/heatmap_conhecimentos.md
    - Heatmap de Horários: tabelas/heatmap_horarios.md
    - Metodologias: planejamento/metodologias.md
    - Plano de Custos: planejamento/plano_custos.md
    - Plano de Risco: gestao_projetos/plano_risco.md
    - Plano de Comunicação: gestao_projetos/plano_comunicacao.md
    - Plano de Qualidade: gestao_projetos/plano_qualidade.md
    - Arquitetura: documentacao/arquitetura.md
    - Estrutura Analítica do Projeto: gestao_projetos/eap.md
    - Diagrama Entidade-relacionamento: diagramas/diagrama_entidade_relacionamento.md
  - Manual de uso:
    - Manual de uso da CLI: manual_uso_cli/cli.md
  - Visão do Produto: 
    - Lean Inception: lean_inception.md
  - Reuniões:
    - Reunião 06/09: atas/reuniao1.md
    - Reunião 12/09: atas/reuniao2.md
    - Reunião 13/09: atas/reuniao3.md
    - Reunião 18/09: atas/reuniao4.md
    - Reunião 20/09: atas/reuniao5.md
    - Reunião 25/09: atas/reuniao6.md
    - Reunião 26/09: atas/reuniao7.md
    - Reunião 27/09: atas/reuniao8.md
    - Reunião 28/09: atas/reuniao9.md
    - Reunião 29/09: atas/reuniao10.md
    - Reunião 30/09: atas/reuniao11.md
    - Reunião 02/10: atas/reuniao12.md
    - Reunião 03/10: atas/reuniao13.md
    - Reunião 04/10: atas/reuniao14.md
  - Sprints:
    - Sprint 00: sprints/sprint00.md
    - Sprint 01:
      - Planejamento: sprints/sprint01p.md
      - Resultado: sprints/sprint01r.md
    - Sprint 02:
      - Planejamento: sprints/sprint02p.md
  - Guia de Contribuição: 
    - Política de Commits: guia_contribuicao/politica_commits.md
    - Política de Branchs: guia_contribuicao/politica_branchs.md
    - Código de conduta: guia_contribuicao/CODE_OF_CONDUCT.md
